### ISSUE TITLE
Add note about goal of article

### ISSUE THREAD

**Issue by mikesol** [meeshkan/introduction-to-property-based-testing#1]
During the sprint planning, we'd decided to shift focus from working on productizing to a quick win, and we narrowed the scope from a Udemy course to a gated self-hosted video to an article. It's not clear to me yet how this article achieves the original goal of the Udemy course (getting people to try out our stuff & getting feedback), and it'd be helpful to have a note about that in this sketch.

1. What hypothesis is being tested with this article?
1. Is there a call-to-action or other way that we will solicit feedback?
1. Will the article incite people to try out Meeshkan or another library?
1. How will the article help us get information that clarifies what we want to build?

There may not be answers to these questions, and it's fine too to say "we wanna write a kickin' piece of content on a theme we're excited about and see if it gets hearts/unicorns/bookmarks on dev.to," which is my usual approach to writing content.  If that's the case, though, and if we've pivoted the focus from the original goals of the sprint (engagement/feedback/quick-win), it should be communicated to the team - it'd be valuable to know why the goal was shifted and what the new goal is.

**Comment by fornwall** [comment]
This was discussed in teams, link for reference: https://teams.microsoft.com/l/message/19:43ad3ac2935249b980ec50f6876f08d0@thread.tacv2/1585203514379?tenantId=0ed0db84-4584-47d8-a696-20d5ae5673b2&groupId=d49f18d0-a756-44a7-9a13-610087521813&parentMessageId=1585203514379&teamName=Marketing&channelName=Online%20course&createdTime=1585203514379
